version: '3.4'

services:
  exchangedb:
    container_name: exchangedb
    environment:
        SA_PASSWORD: "mydatabaseP@ssword"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  nf.exchangerates.mssql.dbup:
    container_name: exchangeDbUp
    restart: "no"
    depends_on:
        - exchangedb

  nf.exchangerates.api:
    container_name: exchangeApi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
    depends_on:
        - exchangedb